/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Group1
 */
public class UserSelection extends javax.swing.JFrame {
    
    private static ServerConnection con;
    
    public UserSelection() {
        initComponents();
        container.removeAll();
        container.add(LoginForm);
        container.repaint();
        container.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        UserSelectionMenu = new javax.swing.JSplitPane();
        LoginTopMenu = new javax.swing.JPanel();
        LoginTopMenuText = new javax.swing.JLabel();
        SignupTopMenu = new javax.swing.JPanel();
        SignupTopMenuText = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        LoginUsername = new javax.swing.JPanel();
        LoginUsernameSeperator = new javax.swing.JSeparator();
        LoginUsernameLabel = new javax.swing.JLabel();
        LoginUsernameInput = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JPanel();
        LoginPasswordSeperator = new javax.swing.JSeparator();
        LoginPasswordLabel = new javax.swing.JLabel();
        LoginPasswordInput = new javax.swing.JPasswordField();
        LoginSubmit = new javax.swing.JPanel();
        LoginSubmitLabel = new javax.swing.JLabel();
        SignupForm = new javax.swing.JPanel();
        SignupUsername = new javax.swing.JPanel();
        SignupUsernameSeperator = new javax.swing.JSeparator();
        SignupUsernameLabel = new javax.swing.JLabel();
        SignupUsernameInput = new javax.swing.JTextField();
        SignupNickname = new javax.swing.JPanel();
        SignupNicknameSeperato = new javax.swing.JSeparator();
        SignupNicknameLabel = new javax.swing.JLabel();
        SignupNicknameInput = new javax.swing.JTextField();
        SignupPassword = new javax.swing.JPanel();
        SignupPasswordSeperator = new javax.swing.JSeparator();
        SignupPasswordLabel = new javax.swing.JLabel();
        SignupPasswordInput = new javax.swing.JPasswordField();
        SignupPasswordConfirm = new javax.swing.JPanel();
        SignupPasswordSeperatorConfirm = new javax.swing.JSeparator();
        SignupPasswordLabelConfirm = new javax.swing.JLabel();
        SignupPasswordInputConfirm = new javax.swing.JPasswordField();
        SignupSubmit = new javax.swing.JPanel();
        SignupSubmitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(355, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bg.setBackground(new java.awt.Color(50, 30, 90));
        bg.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));

        UserSelectionMenu.setBackground(new java.awt.Color(70, 60, 110));
        UserSelectionMenu.setDividerLocation(640);
        UserSelectionMenu.setDividerSize(0);
        UserSelectionMenu.setResizeWeight(0.5);
        UserSelectionMenu.setAlignmentX(0.5F);
        UserSelectionMenu.setAlignmentY(0.5F);
        UserSelectionMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserSelectionMenu.setPreferredSize(new java.awt.Dimension(1280, 50));

        LoginTopMenu.setBackground(new java.awt.Color(90, 60, 140));
        LoginTopMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginTopMenuMouseClicked(evt);
            }
        });

        LoginTopMenuText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LoginTopMenuText.setForeground(new java.awt.Color(230, 230, 230));
        LoginTopMenuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTopMenuText.setText("LOGIN");
        LoginTopMenuText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginTopMenuTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginTopMenuTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginTopMenuTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginTopMenuLayout = new javax.swing.GroupLayout(LoginTopMenu);
        LoginTopMenu.setLayout(LoginTopMenuLayout);
        LoginTopMenuLayout.setHorizontalGroup(
            LoginTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginTopMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginTopMenuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LoginTopMenuLayout.setVerticalGroup(
            LoginTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginTopMenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LoginTopMenuText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        UserSelectionMenu.setLeftComponent(LoginTopMenu);

        SignupTopMenu.setBackground(new java.awt.Color(230, 230, 230));
        SignupTopMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupTopMenuMouseClicked(evt);
            }
        });

        SignupTopMenuText.setBackground(new java.awt.Color(230, 230, 230));
        SignupTopMenuText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SignupTopMenuText.setForeground(new java.awt.Color(90, 60, 140));
        SignupTopMenuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupTopMenuText.setText("SIGNUP");
        SignupTopMenuText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupTopMenuTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupTopMenuTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupTopMenuTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SignupTopMenuLayout = new javax.swing.GroupLayout(SignupTopMenu);
        SignupTopMenu.setLayout(SignupTopMenuLayout);
        SignupTopMenuLayout.setHorizontalGroup(
            SignupTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupTopMenuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SignupTopMenuLayout.setVerticalGroup(
            SignupTopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupTopMenuText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        UserSelectionMenu.setRightComponent(SignupTopMenu);

        container.setBackground(new java.awt.Color(50, 30, 90));
        container.setPreferredSize(new java.awt.Dimension(1280, 670));
        container.setLayout(new java.awt.CardLayout());

        LoginForm.setBackground(new java.awt.Color(50, 30, 90));
        LoginForm.setPreferredSize(new java.awt.Dimension(1280, 670));

        LoginUsername.setBackground(new java.awt.Color(230, 230, 230));
        LoginUsername.setPreferredSize(new java.awt.Dimension(880, 64));

        LoginUsernameSeperator.setBackground(new java.awt.Color(50, 30, 90));
        LoginUsernameSeperator.setForeground(new java.awt.Color(50, 30, 90));
        LoginUsernameSeperator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        LoginUsernameSeperator.setPreferredSize(new java.awt.Dimension(5, 0));

        LoginUsernameLabel.setBackground(new java.awt.Color(50, 30, 90));
        LoginUsernameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LoginUsernameLabel.setForeground(new java.awt.Color(50, 30, 90));
        LoginUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginUsernameLabel.setText("Username");
        LoginUsernameLabel.setToolTipText("");

        LoginUsernameInput.setBackground(new java.awt.Color(230, 230, 230));
        LoginUsernameInput.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LoginUsernameInput.setForeground(new java.awt.Color(50, 30, 90));
        LoginUsernameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginUsernameInput.setBorder(null);

        javax.swing.GroupLayout LoginUsernameLayout = new javax.swing.GroupLayout(LoginUsername);
        LoginUsername.setLayout(LoginUsernameLayout);
        LoginUsernameLayout.setHorizontalGroup(
            LoginUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginUsernameLayout.createSequentialGroup()
                .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginUsernameSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginUsernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );
        LoginUsernameLayout.setVerticalGroup(
            LoginUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginUsernameSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginUsernameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        LoginPassword.setBackground(new java.awt.Color(230, 230, 230));
        LoginPassword.setPreferredSize(new java.awt.Dimension(880, 64));

        LoginPasswordSeperator.setBackground(new java.awt.Color(50, 30, 90));
        LoginPasswordSeperator.setForeground(new java.awt.Color(50, 30, 90));
        LoginPasswordSeperator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        LoginPasswordLabel.setBackground(new java.awt.Color(50, 30, 90));
        LoginPasswordLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LoginPasswordLabel.setForeground(new java.awt.Color(50, 30, 90));
        LoginPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPasswordLabel.setText("Password");

        LoginPasswordInput.setBackground(new java.awt.Color(230, 230, 230));
        LoginPasswordInput.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        LoginPasswordInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginPasswordInput.setBorder(null);
        LoginPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginPasswordInputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout LoginPasswordLayout = new javax.swing.GroupLayout(LoginPassword);
        LoginPassword.setLayout(LoginPasswordLayout);
        LoginPasswordLayout.setHorizontalGroup(
            LoginPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPasswordLayout.createSequentialGroup()
                .addComponent(LoginPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPasswordSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPasswordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
        LoginPasswordLayout.setVerticalGroup(
            LoginPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPasswordSeperator)
            .addComponent(LoginPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginPasswordInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        LoginSubmit.setBackground(new java.awt.Color(90, 50, 130));
        LoginSubmit.setPreferredSize(new java.awt.Dimension(1280, 100));

        LoginSubmitLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LoginSubmitLabel.setForeground(new java.awt.Color(230, 230, 230));
        LoginSubmitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginSubmitLabel.setText("LOGIN");
        LoginSubmitLabel.setPreferredSize(new java.awt.Dimension(1280, 32));
        LoginSubmitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginSubmitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginSubmitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginSubmitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginSubmitLayout = new javax.swing.GroupLayout(LoginSubmit);
        LoginSubmit.setLayout(LoginSubmitLayout);
        LoginSubmitLayout.setHorizontalGroup(
            LoginSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginSubmitLayout.createSequentialGroup()
                .addComponent(LoginSubmitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LoginSubmitLayout.setVerticalGroup(
            LoginSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginSubmitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 223, Short.MAX_VALUE))
            .addComponent(LoginSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(LoginSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        container.add(LoginForm, "card2");

        SignupForm.setBackground(new java.awt.Color(50, 30, 90));
        SignupForm.setPreferredSize(new java.awt.Dimension(1280, 670));

        SignupUsername.setBackground(new java.awt.Color(230, 230, 230));
        SignupUsername.setPreferredSize(new java.awt.Dimension(880, 64));

        SignupUsernameSeperator.setBackground(new java.awt.Color(50, 30, 90));
        SignupUsernameSeperator.setForeground(new java.awt.Color(50, 30, 90));
        SignupUsernameSeperator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        SignupUsernameSeperator.setPreferredSize(new java.awt.Dimension(5, 0));

        SignupUsernameLabel.setBackground(new java.awt.Color(50, 30, 90));
        SignupUsernameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SignupUsernameLabel.setForeground(new java.awt.Color(50, 30, 90));
        SignupUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupUsernameLabel.setText("Username");
        SignupUsernameLabel.setToolTipText("");

        SignupUsernameInput.setBackground(new java.awt.Color(230, 230, 230));
        SignupUsernameInput.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        SignupUsernameInput.setForeground(new java.awt.Color(50, 30, 90));
        SignupUsernameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SignupUsernameInput.setBorder(null);

        javax.swing.GroupLayout SignupUsernameLayout = new javax.swing.GroupLayout(SignupUsername);
        SignupUsername.setLayout(SignupUsernameLayout);
        SignupUsernameLayout.setHorizontalGroup(
            SignupUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupUsernameLayout.createSequentialGroup()
                .addComponent(SignupUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupUsernameSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupUsernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );
        SignupUsernameLayout.setVerticalGroup(
            SignupUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupUsernameSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignupUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignupUsernameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        SignupNickname.setBackground(new java.awt.Color(230, 230, 230));
        SignupNickname.setPreferredSize(new java.awt.Dimension(880, 64));

        SignupNicknameSeperato.setBackground(new java.awt.Color(50, 30, 90));
        SignupNicknameSeperato.setForeground(new java.awt.Color(50, 30, 90));
        SignupNicknameSeperato.setOrientation(javax.swing.SwingConstants.VERTICAL);
        SignupNicknameSeperato.setPreferredSize(new java.awt.Dimension(5, 0));

        SignupNicknameLabel.setBackground(new java.awt.Color(50, 30, 90));
        SignupNicknameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SignupNicknameLabel.setForeground(new java.awt.Color(50, 30, 90));
        SignupNicknameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupNicknameLabel.setText("Nickname");
        SignupNicknameLabel.setToolTipText("");

        SignupNicknameInput.setBackground(new java.awt.Color(230, 230, 230));
        SignupNicknameInput.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        SignupNicknameInput.setForeground(new java.awt.Color(50, 30, 90));
        SignupNicknameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SignupNicknameInput.setBorder(null);

        javax.swing.GroupLayout SignupNicknameLayout = new javax.swing.GroupLayout(SignupNickname);
        SignupNickname.setLayout(SignupNicknameLayout);
        SignupNicknameLayout.setHorizontalGroup(
            SignupNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupNicknameLayout.createSequentialGroup()
                .addComponent(SignupNicknameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupNicknameSeperato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupNicknameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );
        SignupNicknameLayout.setVerticalGroup(
            SignupNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupNicknameSeperato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignupNicknameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignupNicknameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        SignupPassword.setBackground(new java.awt.Color(230, 230, 230));
        SignupPassword.setPreferredSize(new java.awt.Dimension(880, 64));

        SignupPasswordSeperator.setBackground(new java.awt.Color(50, 30, 90));
        SignupPasswordSeperator.setForeground(new java.awt.Color(50, 30, 90));
        SignupPasswordSeperator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SignupPasswordLabel.setBackground(new java.awt.Color(50, 30, 90));
        SignupPasswordLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SignupPasswordLabel.setForeground(new java.awt.Color(50, 30, 90));
        SignupPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupPasswordLabel.setText("Password");

        SignupPasswordInput.setBackground(new java.awt.Color(230, 230, 230));
        SignupPasswordInput.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        SignupPasswordInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SignupPasswordInput.setBorder(null);
        SignupPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SignupPasswordInputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout SignupPasswordLayout = new javax.swing.GroupLayout(SignupPassword);
        SignupPassword.setLayout(SignupPasswordLayout);
        SignupPasswordLayout.setHorizontalGroup(
            SignupPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPasswordLayout.createSequentialGroup()
                .addComponent(SignupPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupPasswordSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupPasswordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
        SignupPasswordLayout.setVerticalGroup(
            SignupPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupPasswordSeperator)
            .addComponent(SignupPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignupPasswordInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        SignupPasswordConfirm.setBackground(new java.awt.Color(230, 230, 230));
        SignupPasswordConfirm.setPreferredSize(new java.awt.Dimension(880, 64));

        SignupPasswordSeperatorConfirm.setBackground(new java.awt.Color(50, 30, 90));
        SignupPasswordSeperatorConfirm.setForeground(new java.awt.Color(50, 30, 90));
        SignupPasswordSeperatorConfirm.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SignupPasswordLabelConfirm.setBackground(new java.awt.Color(50, 30, 90));
        SignupPasswordLabelConfirm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SignupPasswordLabelConfirm.setForeground(new java.awt.Color(50, 30, 90));
        SignupPasswordLabelConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupPasswordLabelConfirm.setText("Confirm Password");

        SignupPasswordInputConfirm.setBackground(new java.awt.Color(230, 230, 230));
        SignupPasswordInputConfirm.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        SignupPasswordInputConfirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SignupPasswordInputConfirm.setBorder(null);
        SignupPasswordInputConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SignupPasswordInputConfirmKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout SignupPasswordConfirmLayout = new javax.swing.GroupLayout(SignupPasswordConfirm);
        SignupPasswordConfirm.setLayout(SignupPasswordConfirmLayout);
        SignupPasswordConfirmLayout.setHorizontalGroup(
            SignupPasswordConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPasswordConfirmLayout.createSequentialGroup()
                .addComponent(SignupPasswordLabelConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupPasswordSeperatorConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupPasswordInputConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
        SignupPasswordConfirmLayout.setVerticalGroup(
            SignupPasswordConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupPasswordSeperatorConfirm)
            .addComponent(SignupPasswordLabelConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignupPasswordInputConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        SignupSubmit.setBackground(new java.awt.Color(90, 50, 130));
        SignupSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignupSubmit.setPreferredSize(new java.awt.Dimension(1280, 100));

        SignupSubmitLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        SignupSubmitLabel.setForeground(new java.awt.Color(230, 230, 230));
        SignupSubmitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupSubmitLabel.setText("SIGNUP");
        SignupSubmitLabel.setPreferredSize(new java.awt.Dimension(1280, 32));
        SignupSubmitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupSubmitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupSubmitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupSubmitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SignupSubmitLayout = new javax.swing.GroupLayout(SignupSubmit);
        SignupSubmit.setLayout(SignupSubmitLayout);
        SignupSubmitLayout.setHorizontalGroup(
            SignupSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupSubmitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        SignupSubmitLayout.setVerticalGroup(
            SignupSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupSubmitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SignupFormLayout = new javax.swing.GroupLayout(SignupForm);
        SignupForm.setLayout(SignupFormLayout);
        SignupFormLayout.setHorizontalGroup(
            SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupFormLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignupUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignupPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignupPasswordConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignupNickname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 223, Short.MAX_VALUE))
            .addComponent(SignupSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        SignupFormLayout.setVerticalGroup(
            SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupFormLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(SignupUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(SignupNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(SignupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(SignupPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(SignupSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        container.add(SignupForm, "card3");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserSelectionMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(container, 1300, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(UserSelectionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, 1300, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginTopMenuTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginTopMenuTextMouseClicked
        // TODO add your handling code here:
        container.removeAll();
        container.add(LoginForm);
        container.repaint();
        container.revalidate();
    }//GEN-LAST:event_LoginTopMenuTextMouseClicked

    private void SignupTopMenuTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupTopMenuTextMouseClicked
        // TODO add your handling code here:
        container.removeAll();
        container.add(SignupForm);
        container.repaint();
        container.revalidate();
    }//GEN-LAST:event_SignupTopMenuTextMouseClicked

    private void LoginPasswordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginPasswordInputKeyPressed
        // TODO add your handling code here:
        try{
            if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        	con.sendMessage("login");
        	String msg = loginAttempt();
        	if (msg.contains("SUCCESS")){
        		GameMain gamegui = new GameMain(con);
        		gamegui.setVisible(true);
        		gamegui.pack();
        		gamegui.setLocationRelativeTo(null);
        		gamegui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        		this.dispose();
        	}else {
        		JOptionPane.showMessageDialog(container,msg,"ERROR",JOptionPane.ERROR_MESSAGE); 
        	}
        }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_LoginPasswordInputKeyPressed

    private void LoginTopMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginTopMenuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_LoginTopMenuMouseClicked

    private void SignupTopMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupTopMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SignupTopMenuMouseClicked

    private void SignupPasswordInputConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SignupPasswordInputConfirmKeyPressed
        // TODO add your handling code here:
        try{
            if (evt.getKeyCode()==KeyEvent.VK_ENTER){
                con.sendMessage("signup");
                String msg = signupAttempt();
                if (msg.contains("SUCCESS")){
                    GameMain gamegui = new GameMain(con);
                    gamegui.setVisible(true);
                    gamegui.pack();
                    gamegui.setLocationRelativeTo(null);
                    gamegui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }else {
                    JOptionPane.showMessageDialog(container,msg,"ERROR",JOptionPane.ERROR_MESSAGE); 
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_SignupPasswordInputConfirmKeyPressed

    private void SignupPasswordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SignupPasswordInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignupPasswordInputKeyPressed

    private void LoginSubmitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSubmitLabelMouseEntered
        // TODO add your handling code here:
        LoginSubmit.setBackground(new Color(110,80,160));
    }//GEN-LAST:event_LoginSubmitLabelMouseEntered

    private void LoginSubmitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSubmitLabelMouseExited
        // TODO add your handling code here:
        LoginSubmit.setBackground(new Color(90,50,130));
    }//GEN-LAST:event_LoginSubmitLabelMouseExited

    private void SignupSubmitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupSubmitLabelMouseEntered
        // TODO add your handling code here:
        SignupSubmit.setBackground(new Color(110,80,160));
    }//GEN-LAST:event_SignupSubmitLabelMouseEntered

    private void SignupSubmitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupSubmitLabelMouseExited
        // TODO add your handling code here:
        SignupSubmit.setBackground(new Color(90,50,130));
    }//GEN-LAST:event_SignupSubmitLabelMouseExited

    private void LoginTopMenuTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginTopMenuTextMouseEntered
        // TODO add your handling code here:
        LoginTopMenu.setBackground(LoginTopMenu.getBackground().brighter());
    }//GEN-LAST:event_LoginTopMenuTextMouseEntered

    private void LoginTopMenuTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginTopMenuTextMouseExited
        // TODO add your handling code here:
        LoginTopMenu.setBackground(LoginTopMenu.getBackground().darker());
    }//GEN-LAST:event_LoginTopMenuTextMouseExited

    private void SignupTopMenuTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupTopMenuTextMouseEntered
        // TODO add your handling code here:
        SignupTopMenu.setBackground(SignupTopMenu.getBackground().darker());
    }//GEN-LAST:event_SignupTopMenuTextMouseEntered

    private void SignupTopMenuTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupTopMenuTextMouseExited
        // TODO add your handling code here:
        SignupTopMenu.setBackground(SignupTopMenu.getBackground().brighter());
    }//GEN-LAST:event_SignupTopMenuTextMouseExited

    private void LoginSubmitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSubmitLabelMouseClicked
        // TODO add your handling code here:
        try{
            con.sendMessage("login");
            String msg = loginAttempt();
            if (msg.contains("SUCCESS")){
                    GameMain gamegui = new GameMain(con);
                    gamegui.setVisible(true);
                    gamegui.pack();
                    gamegui.setLocationRelativeTo(null);
                    gamegui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
            }else {
                    JOptionPane.showMessageDialog(container,msg,"ERROR",JOptionPane.ERROR_MESSAGE); 
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_LoginSubmitLabelMouseClicked

    private void SignupSubmitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupSubmitLabelMouseClicked
        // TODO add your handling code here:
        try{
            con.sendMessage("signup");
            String msg = signupAttempt();
            if (msg.contains("SUCCESS")){
                    GameMain gamegui = new GameMain(con);
                    gamegui.setVisible(true);
                    gamegui.pack();
                    gamegui.setLocationRelativeTo(null);
                    gamegui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
            }else {
                    JOptionPane.showMessageDialog(container,msg,"ERROR",JOptionPane.ERROR_MESSAGE); 
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_SignupSubmitLabelMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try{
            con.sendMessage("leave");
            con.s.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private String loginAttempt() throws Exception {
    	String credentials[]=getLoginCredentials();
    	String username = credentials[0];
    	String password = credentials[1];
        if (username.equals("") || username.equals(" ")) {
        	return "ERROR: Username field is empty";
        }else if (password.equals("") || password.equals(" ")) {
        	return "ERROR: Password field is empty";
        }
    	con.sendMessage(username);
    	con.sendMessage(password);
    	return con.receiveMessage();
    }
    
    private String[] getLoginCredentials(){
        String username = LoginUsernameInput.getText();
        String password = serializePassword(LoginPasswordInput.getPassword());
        String[] credentials = new String[2];
       	credentials[0] = username;
       	credentials[1] = password;        	
        return credentials;
    }
    
    private String signupAttempt() throws Exception {
    	String credentials[]=getSignupCredentials();
    	String username = credentials[0];
    	String password = credentials[1];
    	String password_check = credentials[2];
    	String nickname = credentials[3];
        if (username.equals("") || username.equals(" ")) {
        	return "ERROR: Username field is empty";
        }else if (password.equals("") || password.equals(" ")) {
        	return "ERROR: Password field is empty";
        }else if(!password.equals(password_check)) {
        	return "ERROR: Passwords are not the same";
        }else if (nickname.equals("") || nickname.equals(" ")) {
        	return "ERROR: Nickname field is empty";
        }
    	con.sendMessage(username);
    	con.sendMessage(password);
    	con.sendMessage(nickname);
    	return con.receiveMessage();
    }
    
    private String[] getSignupCredentials(){
        String username = SignupUsernameInput.getText();
        String password = serializePassword(SignupPasswordInput.getPassword());
        String password_check = serializePassword(SignupPasswordInputConfirm.getPassword());
        String nickname = SignupNicknameInput.getText();
        String[] credentials = new String[4];
       	credentials[0] = username;
       	credentials[1] = password; 
       	credentials[2] = password_check;
       	credentials[3] = nickname;
        return credentials;
    }
    
    private String serializePassword(char[] pass){
        String password = "";
        for (int i = 0; i<pass.length;i++){
            password += pass[i];
        }    
        return password;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        /*
        if (args.length <= 1) {
                System.err.println("Pass the server IP and Port as command line argument");
                return;
        }
        */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSelection().setVisible(true);
            }
        });
        
        //Initialize connection
        try {
//                var socket = new Socket("192.168.1.104", 12345);
	        var socket = new Socket(args[0], Integer.parseInt(args[1]));
                con = new ServerConnection(socket);
        }catch (Exception e) {
//        	e.printStackTrace();
            System.out.println("Error: We couldn't connect you to the servers.");
            System.out.println("Make sure you put the correct IP and port numbers.");
            System.exit(ERROR);
	}
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginForm;
    private javax.swing.JPanel LoginPassword;
    private javax.swing.JPasswordField LoginPasswordInput;
    private javax.swing.JLabel LoginPasswordLabel;
    private javax.swing.JSeparator LoginPasswordSeperator;
    private javax.swing.JPanel LoginSubmit;
    private javax.swing.JLabel LoginSubmitLabel;
    private javax.swing.JPanel LoginTopMenu;
    private javax.swing.JLabel LoginTopMenuText;
    private javax.swing.JPanel LoginUsername;
    private javax.swing.JTextField LoginUsernameInput;
    private javax.swing.JLabel LoginUsernameLabel;
    private javax.swing.JSeparator LoginUsernameSeperator;
    private javax.swing.JPanel SignupForm;
    private javax.swing.JPanel SignupNickname;
    private javax.swing.JTextField SignupNicknameInput;
    private javax.swing.JLabel SignupNicknameLabel;
    private javax.swing.JSeparator SignupNicknameSeperato;
    private javax.swing.JPanel SignupPassword;
    private javax.swing.JPanel SignupPasswordConfirm;
    private javax.swing.JPasswordField SignupPasswordInput;
    private javax.swing.JPasswordField SignupPasswordInputConfirm;
    private javax.swing.JLabel SignupPasswordLabel;
    private javax.swing.JLabel SignupPasswordLabelConfirm;
    private javax.swing.JSeparator SignupPasswordSeperator;
    private javax.swing.JSeparator SignupPasswordSeperatorConfirm;
    private javax.swing.JPanel SignupSubmit;
    private javax.swing.JLabel SignupSubmitLabel;
    private javax.swing.JPanel SignupTopMenu;
    private javax.swing.JLabel SignupTopMenuText;
    private javax.swing.JPanel SignupUsername;
    private javax.swing.JTextField SignupUsernameInput;
    private javax.swing.JLabel SignupUsernameLabel;
    private javax.swing.JSeparator SignupUsernameSeperator;
    private javax.swing.JSplitPane UserSelectionMenu;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel container;
    // End of variables declaration//GEN-END:variables
}
